import {Artist} from './artist';
import {ArtPiece} from './art-piece';
export var ARTISTS: Artist[] =
[
    {
        "locationCity": "Houston",
        "description": "Houston artist",
        "id": "56a1b1352310406ca0736f8a",
        "numWorks": "5",
        "firstName": "Cynthia",
        "locationState": "Texas",
        "lastName": "Wisener",
        "works": [
            {
                "description": "black clay",
                "mainFile": "../images/Blue_Head_(1).JPG",
                "price": "400",
                "artist_fname": "Cynthia",
                "name": "Blue Head",
                "files": "['../images/Blue_Head_(1).JPG', '../images/Blue_Head_(2).JPG', '../images/Blue_Head_(3).JPG', '../images/Blue_Head_(4).JPG', '../images/Blue_Head_(5).JPG', '../images/Blue_Head_(6).JPG']",
                "artist_id": "56a1b1352310406ca0736f8a",
                "artist_lname": "Wisener",
                "_id": "56a1b20b2310406d55a8b762",
                "keywords": "['clay', 'man']",
                "numFiles": "186",
                "media": "Sculpture"
            },
            {
                "description": "woman sitting",
                "mainFile": "../images/Crossed_Legged_Woman_(1).JPG",
                "price": "400",
                "artist_fname": "Cynthia",
                "name": "Crossed Legged Woman",
                "files": "['../images/Crossed_Legged_Woman_(1).JPG', '../images/Crossed_Legged_Woman_(2).JPG', '../images/Crossed_Legged_Woman_(3).JPG', '../images/Crossed_Legged_Woman_(4).JPG', '../images/Crossed_Legged_Woman_(5).JPG', '../images/Crossed_Legged_Woman_(6).JPG', '../images/Crossed_Legged_Woman_(7).JPG', '../images/Crossed_Legged_Woman_(8).JPG', '../images/Crossed_Legged_Woman_(9).JPG', '../images/Crossed_Legged_Woman_(10).JPG']",
                "artist_id": "56a1b1352310406ca0736f8a",
                "artist_lname": "Wisener",
                "_id": "56a1b20b2310406d55a8b763",
                "keywords": "['clay', 'woman', 'sitting']",
                "numFiles": "421",
                "media": "Sculpture"
            },
            {
                "description": "Man",
                "mainFile": "../images/David_(1).JPG",
                "price": "400",
                "artist_fname": "Cynthia",
                "name": "David",
                "files": "['../images/David_(1).JPG', '../images/David_(2).JPG', '../images/David_(3).JPG', '../images/David_(4).JPG']",
                "artist_id": "56a1b1352310406ca0736f8a",
                "artist_lname": "Wisener",
                "_id": "56a1b20b2310406d55a8b764",
                "keywords": "['clay', 'man', 'face']",
                "numFiles": "108",
                "media": "Sculpture"
            },
            {
                "description": "Man",
                "mainFile": "../images/Intensity_(1).JPG",
                "price": "400",
                "artist_fname": "Cynthia",
                "name": "Intensity",
                "files": "['../images/Intensity_(1).JPG', '../images/Intensity_(2).JPG', '../images/Intensity_(3).JPG', '../images/Intensity_(4).JPG', '../images/Intensity_(5).JPG', '../images/Intensity_(6).JPG']",
                "artist_id": "56a1b1352310406ca0736f8a",
                "artist_lname": "Wisener",
                "_id": "56a1b20b2310406d55a8b765",
                "keywords": "['clay', 'man', 'face']",
                "numFiles": "186",
                "media": "Sculpture"
            },
            {
                "description": "woman sitting on a stone",
                "mainFile": "../images/Seated_Woman_(1).JPG",
                "price": "400",
                "artist_fname": "Cynthia",
                "name": "Seated Woman",
                "files": "['../images/Seated_Woman_(1).JPG', '../images/Seated_Woman_(2).JPG', '../images/Seated_Woman_(3).JPG', '../images/Seated_Woman_(4).JPG', '../images/Seated_Woman_(5).JPG', '../images/Seated_Woman_(6).JPG', '../images/Seated_Woman_(7).JPG']",
                "artist_id": "56a1b1352310406ca0736f8a",
                "artist_lname": "Wisener",
                "_id": "56a1b20b2310406d55a8b766",
                "keywords": "['clay', 'woman', 'sitting']",
                "numFiles": "238",
                "media": "Sculpture"
            }
        ],
        "profilePic": "../images/profile_1.jpg",
        "media": "Sculpture"
    },
    {
        "description": "I was born and raised in Ft. Worth, Texas  I earned a B. A. and an M. A., in English literature at Rice University. I studied medieval English poetry and prose at the University of Texas in Austin. I love to eat, but would rather read. I am a perennial student of Spanish, and I have a special fondness for the United Kingdom, France, Mexico, Portugal, Brazil, Kenya, and Bulgaria.  <br>  In 2001 I moved back to Houston, Texas, from  Arlington, Virginia, to open a Macromedia and Adobe Authorized Center, Connect Learning, which closed in 2011. <br>I am fortunate to have two sisters,  two sons and four grandchildren.",
        "locationCity": "Houston",
        "id": "56a1b1352310406ca0736f8b",
        "numWorks": "6",
        "firstName": "Sally",
        "locationState": "Texas",
        "lastName": "Smith",
        "works": [
            {
                "description": "Eve in garden",
                "mainFile": "../images/Eve200x293.jpg",
                "price": "N/A",
                "artist_fname": "Sally",
                "name": "Eve",
                "files": "['../images/Eve200x293.jpg']",
                "artist_id": "56a1b1352310406ca0736f8b",
                "artist_lname": "Smith",
                "_id": "56a1b20b2310406d55a8b767",
                "keywords": "['paint', 'eve', 'garden']",
                "numFiles": "28",
                "media": "Paint"
            },
            {
                "description": "Portrait",
                "mainFile": "../images/pioneer200x252.jpg",
                "price": "400",
                "artist_fname": "Sally",
                "name": "Pioneer",
                "files": "['../images/pioneer200x252.jpg']",
                "artist_id": "56a1b1352310406ca0736f8b",
                "artist_lname": "Smith",
                "_id": "56a1b20b2310406d55a8b768",
                "keywords": "['man', 'portrait']",
                "numFiles": "32",
                "media": "Paint"
            },
            {
                "description": "Woman in garden",
                "mainFile": "../images/Garden200x260.jpg",
                "price": "400",
                "artist_fname": "Sally",
                "name": "Garden",
                "files": "['../images/Garden200x260.jpg']",
                "artist_id": "56a1b1352310406ca0736f8b",
                "artist_lname": "Smith",
                "_id": "56a1b20b2310406d55a8b769",
                "keywords": "['Woman', 'sitting', 'garden']",
                "numFiles": "31",
                "media": "Paint"
            },
            {
                "description": "Father and son portrait",
                "mainFile": "../images/FathernSon302x200.jpg",
                "price": "400",
                "artist_fname": "Sally",
                "name": "Father and Son",
                "files": "['../images/FathernSon302x200.jpg']",
                "artist_id": "56a1b1352310406ca0736f8b",
                "artist_lname": "Smith",
                "_id": "56a1b20b2310406d55a8b76a",
                "keywords": "['father', 'son', 'bright']",
                "numFiles": "35",
                "media": "Paint"
            },
            {
                "description": "woman sitting in chair",
                "mainFile": "../images/Stephanie200x260.jpg",
                "price": "400",
                "artist_fname": "Sally",
                "name": "Stephanie",
                "files": "['../images/Stephanie200x260.jpg']",
                "artist_id": "56a1b1352310406ca0736f8b",
                "artist_lname": "Smith",
                "_id": "56a1b20b2310406d55a8b76b",
                "keywords": "['woman', 'sitting']",
                "numFiles": "34",
                "media": "Paint"
            },
            {
                "description": "Adam and Eve",
                "mainFile": "../images/AdamnEve200x268.jpg",
                "price": "400",
                "artist_fname": "Sally",
                "name": "Adam and Eve",
                "files": "['../images/AdamnEve200x268.jpg']",
                "artist_id": "56a1b1352310406ca0736f8b",
                "artist_lname": "Smith",
                "_id": "56a1b20b2310406d55a8b76c",
                "keywords": "['Adam', 'Eve', 'Dark']",
                "numFiles": "33",
                "media": "Paint"
            }
        ],
        "profilePic": "../images/9378171.jpg",
        "media": "Paint"
    },
    {
        "locationCity": "Houston",
        "description": "Houston Artist",
        "id": "56a8218c2310401ce105045a",
        "numWorks": "13",
        "firstName": "Romeo",
        "locationState": "Texas",
        "lastName": "Robinson",
        "works": [
            {
                "description": "Woman smiling with blue hair, newspaper.",
                "mainFile": "../images/romeo_3.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Blue Hair",
                "files": "['../images/romeo_3.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56a824742310401ce105045d",
                "keywords": "['woman', 'hair', 'light', 'newspaper']",
                "numFiles": "25",
                "media": "Paint"
            },
            {
                "description": "Woman staring into distance, newspaper",
                "mainFile": "../images/romeo_4.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Legacy",
                "files": "['../images/romeo_4.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56a824742310401ce105045e",
                "keywords": "['woman', 'hair', 'light', 'newspaper']",
                "numFiles": "25",
                "media": "Paint"
            },
            {
                "description": "Man with full beard.",
                "mainFile": "../images/romeo_5.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Aviator Man",
                "files": "['../images/romeo_5.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56a824742310401ce105045f",
                "keywords": "['man', 'hair', 'light', 'glasses']",
                "numFiles": "25",
                "media": "Paint"
            },
            {
                "description": "Woman staring with newspaper",
                "mainFile": "../images/romeo_1.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Woman",
                "files": "['../images/romeo_1.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56a825402310401ce1050460",
                "keywords": "['woman', 'hair', 'staring', 'newspaper']",
                "numFiles": "25",
                "media": "Paint"
            },
            {
                "description": "Girl with read hair",
                "mainFile": "../images/romeo_7.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Girl with red hair",
                "files": "['../images/romeo_7.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56b5532c2310406de4fc871b",
                "keywords": "['girl', 'hair', 'red', 'blue top']",
                "numFiles": "25",
                "media": "Paint"
            },
            {
                "description": "woman with braids and necklace",
                "mainFile": "../images/romeo_8.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Woman with braids",
                "files": "['../images/romeo_8.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56b5532c2310406de4fc871c",
                "keywords": "['woman', 'braids', 'necklace']",
                "numFiles": "25",
                "media": "Paint"
            },
            {
                "description": "woman staring into distance",
                "mainFile": "../images/romeo_9.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Colorful Headband",
                "files": "['../images/romeo_9.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56b5532c2310406de4fc871d",
                "keywords": "['woman', 'headband', 'big har']",
                "numFiles": "25",
                "media": "Paint"
            },
            {
                "description": "Woman with red hair and green shrit",
                "mainFile": "../images/romeo_10.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Red hair and green shirt",
                "files": "['../images/romeo_10.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56b5532c2310406de4fc871e",
                "keywords": "['woman', 'red hair', 'proud']",
                "numFiles": "26",
                "media": "Paint"
            },
            {
                "description": "woman staring into distance",
                "mainFile": "../images/romeo_11.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Proud Woman",
                "files": "['../images/romeo_11.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56b5532c2310406de4fc871f",
                "keywords": "['woman', 'staring', 'hat']",
                "numFiles": "26",
                "media": "Paint"
            },
            {
                "description": "woman with wrapping",
                "mainFile": "../images/romeo_12.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Woman wrapped",
                "files": "['../images/romeo_12.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56b5532c2310406de4fc8720",
                "keywords": "['woman', 'red', 'wrap']",
                "numFiles": "26",
                "media": "Paint"
            },
            {
                "description": "side profile of woman looking into distance",
                "mainFile": "../images/romeo_13.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Woman side",
                "files": "['../images/romeo_13.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56b5532c2310406de4fc8721",
                "keywords": "['woman', 'side', 'hat', 'earings']",
                "numFiles": "26",
                "media": "Paint"
            },
            {
                "description": "man with hat and parrots",
                "mainFile": "../images/romeo_14.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Man split in two",
                "files": "['../images/romeo_14.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56b5532c2310406de4fc8722",
                "keywords": "['man', 'hat', 'parrots']",
                "numFiles": "26",
                "media": "Paint"
            },
            {
                "description": "woman split",
                "mainFile": "../images/romeo_15.jpg",
                "price": "400",
                "artist_fname": "Romeo",
                "name": "Woman split in two",
                "files": "['../images/romeo_15.jpg']",
                "artist_id": "56a8218c2310401ce105045a",
                "artist_lname": "Robinson",
                "_id": "56b5532c2310406de4fc8723",
                "keywords": "['woman', 'split', 'hat']",
                "numFiles": "26",
                "media": "Paint"
            }
        ],
        "profilePic": "../images/romeo.JPG",
        "media": "Paint"
    },
    {
        "locationCity": "Weston Lakes",
        "description": "Houston artist",
        "id": "56b54c502310406de4fc8714",
        "numWorks": "3",
        "firstName": "Robin E.",
        "locationState": "Texas",
        "lastName": "Mouton",
        "works": [
            {
                "description": "Minotaur",
                "mainFile": "../images/Robin_1.JPG",
                "price": "400",
                "artist_fname": "Robin E.",
                "name": "Deaf Minotaur",
                "files": "['../images/Robin_1.JPG']",
                "artist_id": "56b54c502310406de4fc8714",
                "artist_lname": "Mouton",
                "_id": "56b54e6a2310406de4fc8715",
                "keywords": "['minotaur', 'horns', 'reds']",
                "numFiles": "25",
                "media": "Pastel W/Spray Paint on Rives BFK"
            },
            {
                "description": "Athene Gesture",
                "mainFile": "../images/Robin_2.JPG",
                "price": "100",
                "artist_fname": "Robin E.",
                "name": "Athene Gesture",
                "files": "['../images/Robin_2.JPG']",
                "artist_id": "56b54c502310406de4fc8714",
                "artist_lname": "Mouton",
                "_id": "56b54e6a2310406de4fc8716",
                "keywords": "['woman', 'back', 'athene']",
                "numFiles": "25",
                "media": "Charcoal on Paper"
            },
            {
                "description": "Woman beginning to weave",
                "mainFile": "../images/Robin_3.JPG",
                "price": "200",
                "artist_fname": "Robin E.",
                "name": "Arachne, Beginning to Weave",
                "files": "['../images/Robin_3.JPG']",
                "artist_id": "56b54c502310406de4fc8714",
                "artist_lname": "Mouton",
                "_id": "56b54e6a2310406de4fc8717",
                "keywords": "['arachne', 'weave']",
                "numFiles": "25",
                "media": "Pastel W/Spray Paint on Rives BFK"
            }
        ],
        "profilePic": "../images/IMG_0360Robin.JPG",
        "media": "Pastel W/Spray Paint"
    }
];